### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by alfish2000** [menees/RegExponent#1]
Would it be possible to add a dark theme e.g. depending on the OS Light/Dark setting?

**Comment by menees** [comment]
It's possible, yes, but it's not likely to happen since I don't use dark themes in any apps. WPF doesn't include light/dark themes as a trivial switch, so I'd have to jump through hoops to code it, test it, and support it indefinitely with every UI change I make in the future. It's not worth the trouble to me, and I have way too many coding tasks ahead of me right now.

My wish list for RegExponent includes enhancements that I want on a regular basis like:
* Option to generate code with triple-quoted strings (i.e., [raw string literals](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/raw-string)), 
* Option to generate code with the `[GeneratedRegex]` attribute (for [regex source generators](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators)),
* Highlight matching parenthesis/brace/bracket in the Pattern text box.
* Show all captures within a [repeated group](https://stackoverflow.com/a/11051948/1882616) (not just the last capture).

**Comment by alfish2000** [comment]
Ok. Thanks for your answer and your outlook on the project.
